task: "train" # train, test, benchmarking (to be set up later)
dna_fm_id: "dnabert2" # pretrained dna foundation model id for huggingface

model:
  input_size: 768
  hidden_size: 384
  num_layers: 2

train:
  n_epochs: 10
  grad_accum_iter: 4
  grad_clip: 5.0
  epochs_per_val: 1
  learning_rate: 3e-4
  weight_decay: 1e-3
  beta1: 0.9
  beta2: 0.999

data:
  train_data_path: "data/train.csv"
  val_data_path: "data/val.csv"
  batch_size: 16
  num_workers: 8
  max_length: 3072 # max sequence length to truncate/pad to

log:
  project: explstm
  name: test_run3
  ckpt_path: "."